const express = require('express');
const PDFDocument = require('pdfkit');
const { db } = require('../db');
const { requireAuth } = require('../middleware/auth');

const router = express.Router();
router.use(requireAuth);

function getWeekRange(offset = 0) {
  const now = new Date();
  const dayOfWeek = now.getDay();
  const mondayOffset = dayOfWeek === 0 ? -6 : 1 - dayOfWeek;
  const monday = new Date(now);
  monday.setDate(now.getDate() + mondayOffset - (offset * 7));
  monday.setHours(0, 0, 0, 0);
  const sunday = new Date(monday);
  sunday.setDate(monday.getDate() + 6);
  sunday.setHours(23, 59, 59, 999);
  return {
    start: monday.toISOString().slice(0, 10),
    end: sunday.toISOString().slice(0, 10),
    label: monday.toLocaleDateString('en-GB', { day: 'numeric', month: 'short' }) + ' - ' + sunday.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })
  };
}

router.get('/', async (req, res) => {
  const weeks = [];
  for (let i = 0; i < 4; i++) {
    const w = getWeekRange(i);
    const yogurt = await db.sales.sumByProduct('yogurt', w.start, w.end);
    const tea = await db.sales.sumByProduct('tea', w.start, w.end);
    weeks.push({ start: w.start, end: w.end, label: w.label, yogurt, tea, grandTotal: yogurt.total + tea.total });
  }
  res.render('reports', { weeks, user: req.session });
});

router.get('/pdf/:weekOffset', async (req, res) => {
  const offset = parseInt(req.params.weekOffset) || 0;
  const week = getWeekRange(offset);

  const yogurt = await db.sales.sumByProductGrouped('yogurt', week.start, week.end);
  const tea = await db.sales.sumByProductGrouped('tea', week.start, week.end);
  const yogurtTotals = await db.sales.sumByProduct('yogurt', week.start, week.end);
  const teaTotals = await db.sales.sumByProduct('tea', week.start, week.end);
  const allSales = await db.sales.allInRange(week.start, week.end);

  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', 'attachment; filename="KOVA_Weekly_Report_' + week.start + '_to_' + week.end + '.pdf"');
  doc.pipe(res);

  doc.fontSize(22).font('Helvetica-Bold').text('KOVA Sales Management', { align: 'center' });
  doc.fontSize(12).font('Helvetica').text('Weekly Sales Report', { align: 'center' });
  doc.moveDown(0.3);
  doc.fontSize(11).text('Report Period: ' + week.label, { align: 'center' });
  doc.text('Generated by: ' + req.session.fullName + ' | Date: ' + new Date().toLocaleDateString('en-GB'), { align: 'center' });
  doc.moveDown(0.5);
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#333');
  doc.moveDown(0.8);

  doc.fontSize(14).font('Helvetica-Bold').text('Sales Summary');
  doc.moveDown(0.3);
  doc.fontSize(10).font('Helvetica');

  const sy = doc.y;
  doc.text('Product', 40, sy, { width: 120, underline: true });
  doc.text('Quantity Sold', 160, sy, { width: 100, underline: true, align: 'right' });
  doc.text('Total Revenue (SSP)', 280, sy, { width: 130, underline: true, align: 'right' });
  doc.moveDown(0.6);

  doc.text('Yogurt', 40, doc.y, { width: 120 });
  doc.text(String(yogurtTotals.qty), 160, doc.y, { width: 100, align: 'right' });
  doc.text(yogurtTotals.total.toLocaleString() + ' SSP', 280, doc.y, { width: 130, align: 'right' });
  doc.moveDown(0.4);

  doc.text('Tea', 40, doc.y, { width: 120 });
  doc.text(String(teaTotals.qty), 160, doc.y, { width: 100, align: 'right' });
  doc.text(teaTotals.total.toLocaleString() + ' SSP', 280, doc.y, { width: 130, align: 'right' });
  doc.moveDown(0.5);

  doc.moveTo(40, doc.y).lineTo(410, doc.y).stroke('#999');
  doc.moveDown(0.3);

  const grandQty = yogurtTotals.qty + teaTotals.qty;
  const grandTotal = yogurtTotals.total + teaTotals.total;
  doc.font('Helvetica-Bold').text('Grand Total', 40, doc.y, { width: 120 });
  doc.text(String(grandQty), 160, doc.y, { width: 100, align: 'right' });
  doc.text(grandTotal.toLocaleString() + ' SSP', 280, doc.y, { width: 130, align: 'right' });
  doc.moveDown(1.2);

  doc.fontSize(14).font('Helvetica-Bold').text('Daily Breakdown');
  doc.moveDown(0.3);

  const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
  const startDate = new Date(week.start + 'T00:00:00');

  doc.fontSize(9).font('Helvetica-Bold');
  doc.text('Day', 40, doc.y, { width: 70, underline: true });
  doc.text('Date', 110, doc.y, { width: 60, underline: true });
  doc.text('Yogurt Qty', 170, doc.y, { width: 55, underline: true, align: 'right' });
  doc.text('Yogurt (SSP)', 225, doc.y, { width: 65, underline: true, align: 'right' });
  doc.text('Tea Qty', 290, doc.y, { width: 50, underline: true, align: 'right' });
  doc.text('Tea (SSP)', 340, doc.y, { width: 65, underline: true, align: 'right' });
  doc.text('Day Total', 405, doc.y, { width: 80, underline: true, align: 'right' });
  doc.moveDown(0.5);

  doc.font('Helvetica');
  for (let i = 0; i < 7; i++) {
    const d = new Date(startDate);
    d.setDate(startDate.getDate() + i);
    const ds = d.toISOString().slice(0, 10);
    const yDay = yogurt.find(r => r.sale_date === ds) || { qty: 0, total: 0 };
    const tDay = tea.find(r => r.sale_date === ds) || { qty: 0, total: 0 };
    const dayTotal = yDay.total + tDay.total;

    doc.text(days[i], 40, doc.y, { width: 70 });
    doc.text(ds, 110, doc.y, { width: 60 });
    doc.text(String(yDay.qty), 170, doc.y, { width: 55, align: 'right' });
    doc.text(yDay.total.toLocaleString(), 225, doc.y, { width: 65, align: 'right' });
    doc.text(String(tDay.qty), 290, doc.y, { width: 50, align: 'right' });
    doc.text(tDay.total.toLocaleString(), 340, doc.y, { width: 65, align: 'right' });
    doc.font('Helvetica-Bold').text(dayTotal.toLocaleString(), 405, doc.y, { width: 80, align: 'right' }).font('Helvetica');
    doc.moveDown(0.4);
  }
  doc.moveDown(0.5);

  if (doc.y > 600) doc.addPage();
  doc.fontSize(14).font('Helvetica-Bold').text('Detailed Transactions');
  doc.moveDown(0.3);

  if (allSales.length === 0) {
    doc.fontSize(10).font('Helvetica').text('No transactions recorded for this period.');
  } else {
    doc.fontSize(8).font('Helvetica-Bold');
    doc.text('Date', 40, doc.y, { width: 60, underline: true });
    doc.text('Product', 100, doc.y, { width: 60, underline: true });
    doc.text('Qty', 160, doc.y, { width: 30, underline: true, align: 'right' });
    doc.text('Unit Price', 195, doc.y, { width: 60, underline: true, align: 'right' });
    doc.text('Total', 260, doc.y, { width: 60, underline: true, align: 'right' });
    doc.text('Recorded By', 325, doc.y, { width: 120, underline: true });
    doc.moveDown(0.5);

    doc.font('Helvetica');
    for (const s of allSales) {
      if (doc.y > 750) {
        doc.addPage();
        doc.fontSize(8).font('Helvetica-Bold');
        doc.text('Date', 40, 40, { width: 60, underline: true });
        doc.text('Product', 100, 40, { width: 60, underline: true });
        doc.text('Qty', 160, 40, { width: 30, underline: true, align: 'right' });
        doc.text('Unit Price', 195, 40, { width: 60, underline: true, align: 'right' });
        doc.text('Total', 260, 40, { width: 60, underline: true, align: 'right' });
        doc.text('Recorded By', 325, 40, { width: 120, underline: true });
        doc.moveDown(0.8);
        doc.font('Helvetica');
      }
      doc.text(s.sale_date, 40, doc.y, { width: 60 });
      doc.text(s.product.charAt(0).toUpperCase() + s.product.slice(1), 100, doc.y, { width: 60 });
      doc.text(String(s.quantity), 160, doc.y, { width: 30, align: 'right' });
      doc.text(s.unit_price.toLocaleString(), 195, doc.y, { width: 60, align: 'right' });
      doc.text(s.total_amount.toLocaleString(), 260, doc.y, { width: 60, align: 'right' });
      doc.text(s.full_name, 325, doc.y, { width: 120 });
      doc.moveDown(0.35);
    }
  }

  doc.moveDown(1);
  doc.moveTo(40, doc.y).lineTo(555, doc.y).stroke('#333');
  doc.moveDown(0.3);
  doc.fontSize(8).font('Helvetica').fillColor('#666').text('KOVA Management System - Confidential', { align: 'center' });

  doc.end();
});

module.exports = router;
